### ISSUE TITLE
As a campus event planner I want to be able to advertise for my organizations campus events so I can get more attendance

### ISSUE THREAD

**Issue by ghost** [cse442-spring-2020-offering/cse442-semester-project-main-event#3]
Acceptance Test:
1. Open the app
2. Go to the "Event Finder" page
3. Click on the "Add Event" button
4. Fill in the details about the event
5. Check the box that says "Promote my event"
6. Add the event
7. Go to the "Promoted" page and verify that the event shows up on that page

**Comment by JDsmile** [comment]
Acceptance Test:
1. Open the app
2. Go to the "Event Finder" page
3. Attempt to add an event
4. Before adding the event, check the "Promote my event button"
5. Go back to the "Event Finder" page
6. Click on the "Promoted" button
7. Ensure that the event you just added shows up on the promoted page
