### ISSUE TITLE
Create a Log-in page

### ISSUE THREAD

**Issue by ibnetahir1** [cse442-spring-2020-offering/cse442-semester-project-main-event#32]
Task Test:
1. Open the APP
2. User will see a login screen 
3. User can enter username and password to login
4. User can also click the register button to register an account
5. If user want to use all the functions without register or login, they can click on the SEE ALL EVENTS button

**Comment by JDsmile** [comment]
Task tests:
Open the APP
Input the username and password
User can also click the register button to open the registration page.
User can also click the see all events button to see all the events without sign in.
