### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by JDsmile** [cse442-spring-2020-offering/cse442-semester-project-main-event#85]
Task Test:
In the settings page, user can click the log out button to logout.
When click the logout button, a confirmation message will pop up.
If user confirm the action, the APP will navigate to the login page
If user cancel the action, nothing happens

**Comment by yusenjia** [comment]
Task Test:
In the settings page, user can click the log out button to logout.
When click the logout button, a confirmation message will pop up.
If user confirm the action, the APP will navigate to the login page
If user cancel the action, nothing happens
